### ISSUE TITLE
Per-line mode

### ISSUE THREAD

**Issue by jml** [DRMacIver/each#10]
I'd like to use `each`, except with the input being lines in a file, rather than files in a directory. My use case is that I've got some output from a tool that emits one item per line (in this case, `terraform state list`). 

If I want to use `each` today, I have to do something like `terraform state list | xargs -I'{}' -n1 'touch some-dir/{}'`, which is tricky to remember, and a bit unnecessary.

Instead, I'd like to give each the path to a file, e.g. `each --file=terraform-list-output 'my-command {}'`. I think a natural follow-on from such would be to allow the "file" to be supplied from standard input, e.g. `terraform state list | each --file=- 'my-command {}'`.

Not wedded to the exact spelling, just providing it for illustrative purposes.

**Comment by jml** [comment]
I think I understand & agree with all those thoughts.

What about using line number as a disambiguator? Or even including line number in *all* the directory names? I guess you'd kind of want this as a prefix, which means you'd want to zero pad, which means you'd need to know how many lines there are in advance.

I would very much like to do a PR for this, but I certainly couldn't commit to it.

**Comment by DRMacIver** [comment]
> What about using line number as a disambiguator? Or even including line number in all the directory names?

I think it needs to be more robust than that. Each needs to be able to adapt to changes in the set of files - if you delete a line and rerun it, it shouldn't cause all later lines to need rebuilding. Similarly I think it needs to handle the case where someone deletes or adds a duplicate. 

Perhaps just adding a disambiguator when a line has been seen more than once? So the names would become something like `foo`, `foo-1`, `foo-2`, `...`. Though because each proceeds in random order (for important reasons - it improves predictability) you'd need to disambiguate in order of processing rather than order of lines if you want resume to work correctly.

Hmm. I feel like this ends up kinda confusing. My preference would be to either silently merge duplicates or error on them, but given a good use case for duplicates I could be talked into supporting them.

> which means you'd need to know how many lines there are in advance.

I don't think that's a major problem. Certainly right now `each` assumes it's working on a data set that it knows up front and can fit in memory (though at some point it will start picking up changes to the directory as it runs I guess)

> I would very much like to do a PR for this, but I certainly couldn't commit to it.

I think it would be hard to make a PR that you can't commit to. 😉

**Comment by jml** [comment]
I'm working on this, and have something working that handles the happy case.

**Comment by jml** [comment]
> Likely behaviour in line based mode would be that each line gets added to the output directory as a file called in. Behaviour of each is identical to if you had passed it in as its input file.

Hmm. How would you feel about making `in` a symlink to the original file when running in directory mode?
